### ISSUE TITLE
HeNerator.py  Errno 2 [SOLVED]

### ISSUE THREAD

**Issue by AlejoHarris** [patriciogonzalezvivo/HeNerator#1]
Hi again @patriciogonzalezvivo, this is the error trying to doing it in a Windows PC:

```
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2309, in <module>
    generate(file, args)
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2239, in generate
    shader_in_file = open(shader_filename+'.frag', "r")
FileNotFoundError: [Errno 2] No such file or directory: 'ejndjhwghg6pwxsu9vvskh27yhk011sz.frag'
```

I installed GLSLViewer I think, there is a way to verify that?

**Comment by patriciogonzalezvivo** [comment]
In you console type glslViewer and see if it finds it. GlslViewer needs to be installed on you system path

**Comment by AlejoHarris** [comment]
Thank you @patriciogonzalezvivo, also encounter same issue with FFMpeg, and made the same thing. Thank you! It could be nice to make a note in the Readme that these dependencies need to be installed on the system path, as a recommendation for Windows users that maybe don't know about instlalling this by themselves. Again, thank you!

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/HeNerator/blob/main/README.md#requirements-and-install

**Comment by AlejoHarris** [comment]
Hi @patriciogonzalezvivo, I'm reopening this issue because happened again, with all the dependencies installed in the system PATH

```
./henerator.py black.frag --title Black --duration 10
Warnings while compiling vertex shader:
WARNING: 0:2: '' :  #version directive missing


Warnings while compiling fragment shader:
WARNING: 0:2: '' :  #version directive missing
WARNING: 1:61: Unary operation folding into constant is supported in newer GLSL versions


Warnings while compiling vertex shader:
WARNING: 0:2: '' :  #version directive missing


Warnings while compiling fragment shader:
WARNING: 0:2: '' :  #version directive missing


Traceback (most recent call last):
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2309, in <module>
    generate(file, args)
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2239, in generate
    shader_in_file = open(shader_filename+'.frag', "r")
FileNotFoundError: [Errno 2] No such file or directory: '45yax3k0kel4j7hhk5inftfbkm6fic1z.frag'
```

![image](https://user-images.githubusercontent.com/14794157/134525706-df218dbc-e48b-4abe-8bef-6f824d9a9356.png)

![image](https://user-images.githubusercontent.com/14794157/134525781-2084823a-79e4-4469-b7f7-20f32f9ca7ff.png)

The shader seems to be running normally using the GLSL Viewer extension from VSCode, any idea of what it could be?

**Comment by patriciogonzalezvivo** [comment]
Seams there is an issue with your shader. It's missing the version number. Please try your shaders on [glslViewer](https://github.com/patriciogonzalezvivo/glslViewer) to make sure they run properly

**Comment by AlejoHarris** [comment]
It opens a windows, shows the same warnings and then it closes.

![image](https://user-images.githubusercontent.com/14794157/134527422-4dc9f3eb-64b8-4cfc-a393-96eaf954a533.png)

Is there something in the versioning I may be missing?

**Comment by AlejoHarris** [comment]
What it seems weird to me is that it doesn't have any problem inside VSCode extension

![image](https://user-images.githubusercontent.com/14794157/134527800-be5de0c2-1433-4bd1-a7df-f8f991dd62eb.png)

**Comment by AlejoHarris** [comment]
> Seams there is an issue with your shader. It's missing the version number. Please try your shaders on [glslViewer](https://github.com/patriciogonzalezvivo/glslViewer) to make sure they run properly

Oh I missed this, how can I do this inside my .frag file?

**Comment by AlejoHarris** [comment]
Tried using `#version 300 es` but it still doesn't work

**Comment by AlejoHarris** [comment]
Ok solved this by using de Win32 release of glslViewer, not the x64
