### ISSUE TITLE
Fullscreen height issue

### ISSUE THREAD

**Issue by pablovitamin** [patriciogonzalezvivo/HeNerator#2]
Hello Patricio, I found the way to get the .zip folder. Everything is fine but the fullscreen offfset height problem persists... any clue how to solve it?
![photo_2021-09-22_11-43-13](https://user-images.githubusercontent.com/7560246/134321240-ccbcf382-89b3-4c4f-b28d-81ee6b3c5ba8.jpg)

**Comment by patriciogonzalezvivo** [comment]
Mmm... can't reproduce the error. Do you mind precising what browser/version/OS you are using?

**Comment by pablovitamin** [comment]
using windows 10 - chrome 93.0.4577.82 

The issue seems to be the same I had with the other glsl template.

**Comment by pablovitamin** [comment]
Solved. The problem is just in the preview. After that, works fine. Thanks for everything
