### ISSUE TITLE
WinErrNo 2 after exporting other *.frag file

### ISSUE THREAD

**Issue by AlejoHarris** [patriciogonzalezvivo/HeNerator#3]
Hello again, I'm getting this error now when trying to extract another zip file

```
[image2 @ 000001f02a920c00] Could find no file with path '%05d.png' and index in the range 0-4
%05d.png: No such file or directory
Traceback (most recent call last):
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2309, in <module>
    generate(file, args)
  File "C:\Users\Alejo\Desktop\HeNerator\henerator.py", line 2265, in generate
    zip_file.write('thumbnail.' + thumbnail_ext)
  File "C:\Users\Alejo\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "C:\Users\Alejo\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 501, in from_file
    st = os.stat(filename)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'thumbnail.gif'
```

Translate of the error: The system cannot finde the specified file: 'thumbnail.gif'

**Comment by patriciogonzalezvivo** [comment]
Seams ffmpeg can't find the PNGs. Do you mind confirming that the PNG were generated by GlslViewer? On other words do you see a lot of PNG images?

**Comment by AlejoHarris** [comment]
No, there are no PNGs

**Comment by patriciogonzalezvivo** [comment]
that make me think the glslViewer is not installed or didn't run. (note: glslViewer generates the PNGs)

**Comment by AlejoHarris** [comment]
For some reason, seems like a different *.frag file worked, but that one specifically didn´t work, so I would asume it´s because of that file. Closing this issue. Great work Patricio!

**Comment by patriciogonzalezvivo** [comment]
Makes sense if the shader fails everything will follow... you can use glslViewer to test your shaders
